# Generated by Django 4.1 on 2022-08-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_start',
        ),
    ]
