# Generated by Django 4.1 on 2022-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_product_offer_end_remove_product_offer_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_end',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
