# Generated by Django 4.1 on 2022-08-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_product_offer_end_product_offer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_collection',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('On sale', 'On sale'), ('Top selling', 'Top selling'), ('Deals', 'Deals')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(blank=True, related_name='product_types', to='userapp.product_type'),
        ),
    ]
