# Generated by Django 4.1 on 2022-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_slider_product_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_collection',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('On sale', 'On sale'), ('Top selling', 'Top selling'), ('Deals', 'Deals'), ('Clearance', 'Clearance')], max_length=100),
        ),
    ]
