# Generated by Django 4.1 on 2022-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_product_pro_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=models.ManyToManyField(blank=True, to='userapp.banner'),
        ),
        migrations.AlterField(
            model_name='events',
            name='slider',
            field=models.ManyToManyField(blank=True, to='userapp.slider'),
        ),
    ]
