# Generated by Django 4.1 on 2022-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_events_banner_alter_events_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
