# Generated by Django 4.1 on 2022-08-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_events_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.product'),
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
