# Generated by Django 4.1 on 2022-08-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_events_product_alter_events_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.events'),
        ),
    ]
