# Generated by Django 4.1 on 2022-08-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_events_banner_remove_events_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='userapp.events'),
        ),
    ]
