# Generated by Django 4.1 on 2022-08-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_product_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='events',
        ),
        migrations.AddField(
            model_name='events',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='userapp.product'),
        ),
    ]
