# Generated by Django 4.1 on 2022-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_remove_product_events_events_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='events',
        ),
        migrations.AddField(
            model_name='events',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='userapp.product'),
        ),
    ]
