# Generated by Django 4.1 on 2022-08-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_remove_events_product_product_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='banner',
        ),
        migrations.AddField(
            model_name='events',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.banner'),
        ),
    ]
