# Generated by Django 4.1 on 2022-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_remove_events_banner_events_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='userapp.product'),
        ),
    ]
