# Generated by Django 4.1 on 2022-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_alter_orders_delivart_status_alter_orders_order_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='icon',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
