# Generated by Django 4.1 on 2022-09-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_catagory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
